### PR TITLE
Allow loaddata to use represent.opennorth.ca for BOUNDARY_SET data

### PR DESCRIPTION
**Pull request by patcon**
Canadian councilmatic instances could pull boundary info from here. The `external_id` is slightly different, but seems pretty minor. As far as I can tell, https://scrapers.herokuapp.com doesn't have boundary data right now (?)

cc: @jpmckinney

### CODE REVIEW

**Comment by jpmckinney** [comment]
No, since Heroku has no persistent filesystem, and has limits of the filesize of deployments, we'd have to write a script to download and then loadshapefiles to get the data into the Heroku OCD API deployment - instead of just reading from a gitsubmodule.

**Comment by patcon** [comment]
Cool, thanks. So to confirm, are you +1 on allowing councilmatic to loaddata from represent API?

**Comment by jpmckinney** [comment]
Makes sense to me for the OCD API to not necessarily be the same as the Represent Boundaries API

**Comment by cathydeng** [comment]
loading boundaries from the represent api seems very toronto-specific, & as such, I don't think it belongs in django-councilmatic

perhaps it would make more sense to load toronto boundaries in a custom toronto loading task. we do something like this for chicago (also I'm just realizing that this is not documented anywhere, so I'll get on that)

relevant code: https://github.com/datamade/chi-councilmatic/blob/master/chicago/management/commands/fixdata.py

after running `python manage.py loaddata` we run `python manage.py fixdata` - you could write something similar for toronto

**Comment by patcon** [comment]
It's actually Canada-specific, as the represent API has boundary sets for all Canadian jurisdictions. I could pull it into Toronto, but it really is bigger than us.

If you're still firm on that, I'm happy to write a Canada-specific task and keep it in Toronto's app

**Comment by cathydeng** [comment]
actually jk - I thought represent was a separate api, but just talked to @fgregg & he told me that ocd already supports the represent api & just has a diff endpoint for it.

if boundaries are just a diff endpoint but still using ocd, it def makes sense to have this live in django-councilmatic.

can you re-write this to keep `base_url` as is, & instead have a setting for the boundary endpoint w/ code for handling that appropriately?

**Comment by cathydeng** [comment]
nvm, misunderstood the relationship between ocd & represent - this PR is fine as is

**Pull request merged**
