### PR TITLE
Allow OCDAPI base url to be set in loaddata arg

### PR DESCRIPTION
**Pull request by patcon**
So we can load data from our own imago api's, perhaps locally.

### CODE REVIEW

**Comment by fgregg** [comment]
I think this should be done in the local councilmatic's setting file. You will not really want to use more than one endpoint in practice.

**Comment by patcon** [comment]
Ok, cool. Done and done

**Comment by patcon** [comment]
bump? ready for review

**Comment by patcon** [comment]
Ok, force-pushed a fix. Sorry, it was broken before -- assumed it was super-simple, and didn't test.

Tested and works now. Would be great to get this merged so that I can get folks set up using mainline at the weekly hack night tonight :)

**Comment by fgregg** [comment]
Looks good.

**Comment by patcon** [comment]
Thanks a bunch @fgregg!

**Pull request merged**
